### ISSUE TITLE
rgba with alpha channel more than 2 Precision

### ISSUE THREAD

**Issue by dtSniper** [ozdemirburak/iris#19]
If you try to create a RGBA Object with more as 2 Precision for the alphachannel you will get an error that this isn't a correct rgba value.

This can be avoided by fixing the Precision accordigly.
Class \Traits\AlphaTrait:
you could just change the fixPrecision function:
```
protected function fixPrecision($color)
    {
        if (strpos($color, ',') !== false) {
            $parts = explode(',', $color);
            $parts[3] = strpos($parts[3], '.') === false ? $parts[3] . '.0' : $parts[3];
            $parts[3] = round($parts[3], 2);
            $color = implode(',', $parts);
        }
        return $color;
    }
```

**Comment by ozdemirburak** [comment]
Hi, thanks for reporting this. I'd be happy to accept this fix if you send a pull request.
