### ISSUE TITLE
css color transparent

### ISSUE THREAD

**Issue by dtSniper** [ozdemirburak/iris#22]
The system doesn't know transparent as a color for a fully transparent color.

**Comment by ozdemirburak** [comment]
Correct me if I am wrong, but I think there is not a global solution to this? You can just replace the transparent with a rgba or hsla string. So this should be up to developer? 

On the other hand, we can add a new if else block to [Factory](https://github.com/ozdemirburak/iris/blob/master/src/Color/Factory.php) to replace an exact transparent  string with `rgba(0, 0, 0, 0)`?

**Comment by dtSniper** [comment]
We have the /Helper/DefinedColor Class which is used to transform CSS color names into colors. 
we can have it either in the factory or in the rgba class itself that it check for transparent and transforms it.

Obviously it would be possible to do that with an if statement before using iris. But I think it would be better if we check it directly. 
I'm using Spectrum as color picker and there the system transforms a rgba(x,x,x, 0.0) value into transparent and only transforms it if the user selects the color picker. Defnitly not the best way to handle that from the side of the color picker but if iris can deal with transparent as a name just like it can with red, green etc, that would be awesome.

**Comment by ozdemirburak** [comment]
The problem with the DefinedColor color declaration is, the transparent is not a color and does not have an RGB value. And another problem here for the `rgba(x, x, x, 0.0)` declaration, the choice of x does not change the fact that the output will be transparent as long as the fourth parameter is 0. So, I think assigning something default for transparent should be the developer's choice, not ours.

**Comment by dtSniper** [comment]
Understandable, was just wondering as some devs might not understand why green etc is possible but not transparent. But we can close this and I wil add that edge case in our website

**Comment by ozdemirburak** [comment]
Yeah, you are definitely right. I will add a section about that in the README as well.
