### ISSUE TITLE
Implement Missing Color Methods

### ISSUE THREAD

**Issue by ozdemirburak** [ozdemirburak/iris#23]
We may add some of the missing color methods like [fade](https://github.com/less/less-docs/blob/master/content/functions/color-operations.md#fade), [fadeIn](https://github.com/less/less-docs/blob/master/content/functions/color-operations.md#fadein), and [fadeOut](https://github.com/less/less-docs/blob/master/content/functions/color-operations.md#fadeout). 

Current Implementation Status:

- [x] [fade](https://github.com/less/less.js/blob/2c5e4dd9b9fbe6e5a4ef0c57c827e1ac3443ef0c/packages/less/src/less/functions/color.js#L283)
- [x] [fadeIn](https://github.com/less/less.js/blob/2c5e4dd9b9fbe6e5a4ef0c57c827e1ac3443ef0c/packages/less/src/less/functions/color.js#L259)
- [x] [fadeOut](https://github.com/less/less.js/blob/2c5e4dd9b9fbe6e5a4ef0c57c827e1ac3443ef0c/packages/less/src/less/functions/color.js#L271)

**Comment by khamer** [comment]
Let me know if the above pull request works for you - thanks - happy Hacktoberfest!
