### ISSUE TITLE
Handling 8 character hex codes

### ISSUE THREAD

**Issue by perrelet** [ozdemirburak/iris#28]
Hello,

The library appears unable to handle 8 character hex values such as `#8c23ceff`

When passing such a value to the factory constructor, it throws an _**Invalid HEX value**_ fatal error...

Is there a possible fix for this?

Thankyou!

**Comment by samandeggs** [comment]
+1 this seems like an oversight - if anything there should just be a basic regex check and fail gracefully. Having a whole page fail because of an incorrect colour is quite useless when plugged into a user input.
