### ISSUE TITLE
Invalid alpha value due to locale 

### ISSUE THREAD

**Issue by Gecko-Web** [ozdemirburak/iris#38]
When an rgba or hsla color is output as string, the alpha value can be invalid due to the defined LC_NUMERIC locale

```
setlocale(LC_NUMERIC,'en');
$rgba = new Rgba('rgba(255,0,0,0.3)')
$rgba->__toString() // = > rgba(255,0,0,0.3)
```
```
setlocale(LC_NUMERIC,'fr');
$rgba = new Rgba('rgba(255,0,0,0.3)')
$rgba->__toString() // => rgba(255,0,0,0,3)
```

**Comment by NikarashiHatsu** [comment]
Apparently, this issue only exists on PHP7.
It fixed on PHP8 when locale-independent was implemented https://php.watch/versions/8.0/float-to-string-locale-independent.

But I'll be working on to fix this issue.

**Comment by ozdemirburak** [comment]
As you know, there is a [php-7](https://github.com/ozdemirburak/iris/tree/php-7) branch, but it isn't maintained. Feel free to send a PR to that branch if you work on it.

**Comment by NikarashiHatsu** [comment]
I did a PR to the branch. Technically, it sets the `setlocale()` to `C` temporarily just to fetch the "locale-safe alpha channel", then it reverts back to the machine's locale.

That's the best approach I had in mind. Let me know if you have better approach.

**Comment by ozdemirburak** [comment]
Thanks, @NikarashiHatsu. Looks perfect.
