### ISSUE TITLE
Warning of PHP Deprecated

### ISSUE THREAD

**Issue by nam-co** [ozdemirburak/iris#39]
Hi, thanks for the work on the package, I just installed, but trying it out I found that echo $hex->fade(90)->toHexa();

Produces the error: PHP Deprecated:  Implicit conversion from float 229.5 to int loses precision in /ozdemirburak/iris/src/Traits/AlphaTrait.php

**Comment by NikarashiHatsu** [comment]
Anyway, could you add the `hacktoberfest-accepted` label to my contributions? 😅🙏

**Comment by ozdemirburak** [comment]
Sure, just added that label to all your pull requests. 

If you're looking for more issues, feel free to have a look at this well: https://github.com/ozdemirburak/json-csv/issues/17

Thanks a lot for your great contributions.

**Comment by NikarashiHatsu** [comment]
Sure thing, it was fun to contribute!
