### ISSUE TITLE
Fixing Issues for Hacktoberfest

### ISSUE THREAD

**Issue by ozdemirburak** [ozdemirburak/iris#43]
There are currently four issues that can be grouped here for Hacktoberfest.

1. ~Implement toCmyk method (#36)~
2. ~Fix rgba()->toHexa~ and hlsa()->toHexa not working as expected (#37)
3. ~Fix invalid alpha value due to locale (#38)~
4. ~Implement clone method (#42)~

Some of these issues are easy to implement, and some require extra work. 

Feel free to pick one and work on it; no need to ask if you can work on it or not.

**Comment by NikarashiHatsu** [comment]
Hi, I create a PR regarding #36 and #42.
I didn't really understand what's wrong with #37 and #38 since it works on my machine.
